/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package business.model.strategy;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class BusinessModelStrategy extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -6305860820886658986L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BusinessModelStrategy\",\"namespace\":\"business.model.strategy\",\"fields\":[{\"name\":\"avro_fingerprint\",\"type\":\"long\"},{\"name\":\"index_ipid\",\"type\":\"string\"},{\"name\":\"last_update_timestamp\",\"type\":\"long\",\"logical-type\":\"time-micros\"},{\"name\":\"last_update_loginid\",\"type\":\"string\"},{\"name\":\"partner_ipid\",\"type\":\"string\"},{\"name\":\"drivers\",\"type\":\"string\"},{\"name\":\"competencies\",\"type\":\"string\"},{\"name\":\"capabilities\",\"type\":\"string\"},{\"name\":\"client_structure\",\"type\":\"string\"},{\"name\":\"goals\",\"type\":\"string\"},{\"name\":\"sales_market_region\",\"type\":[\"null\",{\"type\":\"enum\",\"name\":\"code\",\"symbols\":[\"M49_150\",\"M49_142\",\"M49_021\",\"M49_756\",\"other\"]}]},{\"name\":\"sales_country_150\",\"type\":[\"null\",{\"type\":\"array\",\"items\":\"string\"}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<BusinessModelStrategy> ENCODER =
      new BinaryMessageEncoder<BusinessModelStrategy>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<BusinessModelStrategy> DECODER =
      new BinaryMessageDecoder<BusinessModelStrategy>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<BusinessModelStrategy> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<BusinessModelStrategy> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<BusinessModelStrategy> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<BusinessModelStrategy>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this BusinessModelStrategy to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a BusinessModelStrategy from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a BusinessModelStrategy instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static BusinessModelStrategy fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public long avro_fingerprint;
  @Deprecated public java.lang.CharSequence index_ipid;
  @Deprecated public long last_update_timestamp;
  @Deprecated public java.lang.CharSequence last_update_loginid;
  @Deprecated public java.lang.CharSequence partner_ipid;
  @Deprecated public java.lang.CharSequence drivers;
  @Deprecated public java.lang.CharSequence competencies;
  @Deprecated public java.lang.CharSequence capabilities;
  @Deprecated public java.lang.CharSequence client_structure;
  @Deprecated public java.lang.CharSequence goals;
  @Deprecated public business.model.strategy.code sales_market_region;
  @Deprecated public java.util.List<java.lang.CharSequence> sales_country_150;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public BusinessModelStrategy() {}

  /**
   * All-args constructor.
   * @param avro_fingerprint The new value for avro_fingerprint
   * @param index_ipid The new value for index_ipid
   * @param last_update_timestamp The new value for last_update_timestamp
   * @param last_update_loginid The new value for last_update_loginid
   * @param partner_ipid The new value for partner_ipid
   * @param drivers The new value for drivers
   * @param competencies The new value for competencies
   * @param capabilities The new value for capabilities
   * @param client_structure The new value for client_structure
   * @param goals The new value for goals
   * @param sales_market_region The new value for sales_market_region
   * @param sales_country_150 The new value for sales_country_150
   */
  public BusinessModelStrategy(java.lang.Long avro_fingerprint, java.lang.CharSequence index_ipid, java.lang.Long last_update_timestamp, java.lang.CharSequence last_update_loginid, java.lang.CharSequence partner_ipid, java.lang.CharSequence drivers, java.lang.CharSequence competencies, java.lang.CharSequence capabilities, java.lang.CharSequence client_structure, java.lang.CharSequence goals, business.model.strategy.code sales_market_region, java.util.List<java.lang.CharSequence> sales_country_150) {
    this.avro_fingerprint = avro_fingerprint;
    this.index_ipid = index_ipid;
    this.last_update_timestamp = last_update_timestamp;
    this.last_update_loginid = last_update_loginid;
    this.partner_ipid = partner_ipid;
    this.drivers = drivers;
    this.competencies = competencies;
    this.capabilities = capabilities;
    this.client_structure = client_structure;
    this.goals = goals;
    this.sales_market_region = sales_market_region;
    this.sales_country_150 = sales_country_150;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return avro_fingerprint;
    case 1: return index_ipid;
    case 2: return last_update_timestamp;
    case 3: return last_update_loginid;
    case 4: return partner_ipid;
    case 5: return drivers;
    case 6: return competencies;
    case 7: return capabilities;
    case 8: return client_structure;
    case 9: return goals;
    case 10: return sales_market_region;
    case 11: return sales_country_150;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: avro_fingerprint = (java.lang.Long)value$; break;
    case 1: index_ipid = (java.lang.CharSequence)value$; break;
    case 2: last_update_timestamp = (java.lang.Long)value$; break;
    case 3: last_update_loginid = (java.lang.CharSequence)value$; break;
    case 4: partner_ipid = (java.lang.CharSequence)value$; break;
    case 5: drivers = (java.lang.CharSequence)value$; break;
    case 6: competencies = (java.lang.CharSequence)value$; break;
    case 7: capabilities = (java.lang.CharSequence)value$; break;
    case 8: client_structure = (java.lang.CharSequence)value$; break;
    case 9: goals = (java.lang.CharSequence)value$; break;
    case 10: sales_market_region = (business.model.strategy.code)value$; break;
    case 11: sales_country_150 = (java.util.List<java.lang.CharSequence>)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'avro_fingerprint' field.
   * @return The value of the 'avro_fingerprint' field.
   */
  public long getAvroFingerprint() {
    return avro_fingerprint;
  }


  /**
   * Sets the value of the 'avro_fingerprint' field.
   * @param value the value to set.
   */
  public void setAvroFingerprint(long value) {
    this.avro_fingerprint = value;
  }

  /**
   * Gets the value of the 'index_ipid' field.
   * @return The value of the 'index_ipid' field.
   */
  public java.lang.CharSequence getIndexIpid() {
    return index_ipid;
  }


  /**
   * Sets the value of the 'index_ipid' field.
   * @param value the value to set.
   */
  public void setIndexIpid(java.lang.CharSequence value) {
    this.index_ipid = value;
  }

  /**
   * Gets the value of the 'last_update_timestamp' field.
   * @return The value of the 'last_update_timestamp' field.
   */
  public long getLastUpdateTimestamp() {
    return last_update_timestamp;
  }


  /**
   * Sets the value of the 'last_update_timestamp' field.
   * @param value the value to set.
   */
  public void setLastUpdateTimestamp(long value) {
    this.last_update_timestamp = value;
  }

  /**
   * Gets the value of the 'last_update_loginid' field.
   * @return The value of the 'last_update_loginid' field.
   */
  public java.lang.CharSequence getLastUpdateLoginid() {
    return last_update_loginid;
  }


  /**
   * Sets the value of the 'last_update_loginid' field.
   * @param value the value to set.
   */
  public void setLastUpdateLoginid(java.lang.CharSequence value) {
    this.last_update_loginid = value;
  }

  /**
   * Gets the value of the 'partner_ipid' field.
   * @return The value of the 'partner_ipid' field.
   */
  public java.lang.CharSequence getPartnerIpid() {
    return partner_ipid;
  }


  /**
   * Sets the value of the 'partner_ipid' field.
   * @param value the value to set.
   */
  public void setPartnerIpid(java.lang.CharSequence value) {
    this.partner_ipid = value;
  }

  /**
   * Gets the value of the 'drivers' field.
   * @return The value of the 'drivers' field.
   */
  public java.lang.CharSequence getDrivers() {
    return drivers;
  }


  /**
   * Sets the value of the 'drivers' field.
   * @param value the value to set.
   */
  public void setDrivers(java.lang.CharSequence value) {
    this.drivers = value;
  }

  /**
   * Gets the value of the 'competencies' field.
   * @return The value of the 'competencies' field.
   */
  public java.lang.CharSequence getCompetencies() {
    return competencies;
  }


  /**
   * Sets the value of the 'competencies' field.
   * @param value the value to set.
   */
  public void setCompetencies(java.lang.CharSequence value) {
    this.competencies = value;
  }

  /**
   * Gets the value of the 'capabilities' field.
   * @return The value of the 'capabilities' field.
   */
  public java.lang.CharSequence getCapabilities() {
    return capabilities;
  }


  /**
   * Sets the value of the 'capabilities' field.
   * @param value the value to set.
   */
  public void setCapabilities(java.lang.CharSequence value) {
    this.capabilities = value;
  }

  /**
   * Gets the value of the 'client_structure' field.
   * @return The value of the 'client_structure' field.
   */
  public java.lang.CharSequence getClientStructure() {
    return client_structure;
  }


  /**
   * Sets the value of the 'client_structure' field.
   * @param value the value to set.
   */
  public void setClientStructure(java.lang.CharSequence value) {
    this.client_structure = value;
  }

  /**
   * Gets the value of the 'goals' field.
   * @return The value of the 'goals' field.
   */
  public java.lang.CharSequence getGoals() {
    return goals;
  }


  /**
   * Sets the value of the 'goals' field.
   * @param value the value to set.
   */
  public void setGoals(java.lang.CharSequence value) {
    this.goals = value;
  }

  /**
   * Gets the value of the 'sales_market_region' field.
   * @return The value of the 'sales_market_region' field.
   */
  public business.model.strategy.code getSalesMarketRegion() {
    return sales_market_region;
  }


  /**
   * Sets the value of the 'sales_market_region' field.
   * @param value the value to set.
   */
  public void setSalesMarketRegion(business.model.strategy.code value) {
    this.sales_market_region = value;
  }

  /**
   * Gets the value of the 'sales_country_150' field.
   * @return The value of the 'sales_country_150' field.
   */
  public java.util.List<java.lang.CharSequence> getSalesCountry150() {
    return sales_country_150;
  }


  /**
   * Sets the value of the 'sales_country_150' field.
   * @param value the value to set.
   */
  public void setSalesCountry150(java.util.List<java.lang.CharSequence> value) {
    this.sales_country_150 = value;
  }

  /**
   * Creates a new BusinessModelStrategy RecordBuilder.
   * @return A new BusinessModelStrategy RecordBuilder
   */
  public static business.model.strategy.BusinessModelStrategy.Builder newBuilder() {
    return new business.model.strategy.BusinessModelStrategy.Builder();
  }

  /**
   * Creates a new BusinessModelStrategy RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new BusinessModelStrategy RecordBuilder
   */
  public static business.model.strategy.BusinessModelStrategy.Builder newBuilder(business.model.strategy.BusinessModelStrategy.Builder other) {
    if (other == null) {
      return new business.model.strategy.BusinessModelStrategy.Builder();
    } else {
      return new business.model.strategy.BusinessModelStrategy.Builder(other);
    }
  }

  /**
   * Creates a new BusinessModelStrategy RecordBuilder by copying an existing BusinessModelStrategy instance.
   * @param other The existing instance to copy.
   * @return A new BusinessModelStrategy RecordBuilder
   */
  public static business.model.strategy.BusinessModelStrategy.Builder newBuilder(business.model.strategy.BusinessModelStrategy other) {
    if (other == null) {
      return new business.model.strategy.BusinessModelStrategy.Builder();
    } else {
      return new business.model.strategy.BusinessModelStrategy.Builder(other);
    }
  }

  /**
   * RecordBuilder for BusinessModelStrategy instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BusinessModelStrategy>
    implements org.apache.avro.data.RecordBuilder<BusinessModelStrategy> {

    private long avro_fingerprint;
    private java.lang.CharSequence index_ipid;
    private long last_update_timestamp;
    private java.lang.CharSequence last_update_loginid;
    private java.lang.CharSequence partner_ipid;
    private java.lang.CharSequence drivers;
    private java.lang.CharSequence competencies;
    private java.lang.CharSequence capabilities;
    private java.lang.CharSequence client_structure;
    private java.lang.CharSequence goals;
    private business.model.strategy.code sales_market_region;
    private java.util.List<java.lang.CharSequence> sales_country_150;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(business.model.strategy.BusinessModelStrategy.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.avro_fingerprint)) {
        this.avro_fingerprint = data().deepCopy(fields()[0].schema(), other.avro_fingerprint);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.index_ipid)) {
        this.index_ipid = data().deepCopy(fields()[1].schema(), other.index_ipid);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.last_update_timestamp)) {
        this.last_update_timestamp = data().deepCopy(fields()[2].schema(), other.last_update_timestamp);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.last_update_loginid)) {
        this.last_update_loginid = data().deepCopy(fields()[3].schema(), other.last_update_loginid);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.partner_ipid)) {
        this.partner_ipid = data().deepCopy(fields()[4].schema(), other.partner_ipid);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.drivers)) {
        this.drivers = data().deepCopy(fields()[5].schema(), other.drivers);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.competencies)) {
        this.competencies = data().deepCopy(fields()[6].schema(), other.competencies);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.capabilities)) {
        this.capabilities = data().deepCopy(fields()[7].schema(), other.capabilities);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.client_structure)) {
        this.client_structure = data().deepCopy(fields()[8].schema(), other.client_structure);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.goals)) {
        this.goals = data().deepCopy(fields()[9].schema(), other.goals);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.sales_market_region)) {
        this.sales_market_region = data().deepCopy(fields()[10].schema(), other.sales_market_region);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.sales_country_150)) {
        this.sales_country_150 = data().deepCopy(fields()[11].schema(), other.sales_country_150);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
    }

    /**
     * Creates a Builder by copying an existing BusinessModelStrategy instance
     * @param other The existing instance to copy.
     */
    private Builder(business.model.strategy.BusinessModelStrategy other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.avro_fingerprint)) {
        this.avro_fingerprint = data().deepCopy(fields()[0].schema(), other.avro_fingerprint);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.index_ipid)) {
        this.index_ipid = data().deepCopy(fields()[1].schema(), other.index_ipid);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.last_update_timestamp)) {
        this.last_update_timestamp = data().deepCopy(fields()[2].schema(), other.last_update_timestamp);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.last_update_loginid)) {
        this.last_update_loginid = data().deepCopy(fields()[3].schema(), other.last_update_loginid);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.partner_ipid)) {
        this.partner_ipid = data().deepCopy(fields()[4].schema(), other.partner_ipid);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.drivers)) {
        this.drivers = data().deepCopy(fields()[5].schema(), other.drivers);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.competencies)) {
        this.competencies = data().deepCopy(fields()[6].schema(), other.competencies);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.capabilities)) {
        this.capabilities = data().deepCopy(fields()[7].schema(), other.capabilities);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.client_structure)) {
        this.client_structure = data().deepCopy(fields()[8].schema(), other.client_structure);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.goals)) {
        this.goals = data().deepCopy(fields()[9].schema(), other.goals);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.sales_market_region)) {
        this.sales_market_region = data().deepCopy(fields()[10].schema(), other.sales_market_region);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.sales_country_150)) {
        this.sales_country_150 = data().deepCopy(fields()[11].schema(), other.sales_country_150);
        fieldSetFlags()[11] = true;
      }
    }

    /**
      * Gets the value of the 'avro_fingerprint' field.
      * @return The value.
      */
    public long getAvroFingerprint() {
      return avro_fingerprint;
    }


    /**
      * Sets the value of the 'avro_fingerprint' field.
      * @param value The value of 'avro_fingerprint'.
      * @return This builder.
      */
    public business.model.strategy.BusinessModelStrategy.Builder setAvroFingerprint(long value) {
      validate(fields()[0], value);
      this.avro_fingerprint = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'avro_fingerprint' field has been set.
      * @return True if the 'avro_fingerprint' field has been set, false otherwise.
      */
    public boolean hasAvroFingerprint() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'avro_fingerprint' field.
      * @return This builder.
      */
    public business.model.strategy.BusinessModelStrategy.Builder clearAvroFingerprint() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'index_ipid' field.
      * @return The value.
      */
    public java.lang.CharSequence getIndexIpid() {
      return index_ipid;
    }


    /**
      * Sets the value of the 'index_ipid' field.
      * @param value The value of 'index_ipid'.
      * @return This builder.
      */
    public business.model.strategy.BusinessModelStrategy.Builder setIndexIpid(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.index_ipid = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'index_ipid' field has been set.
      * @return True if the 'index_ipid' field has been set, false otherwise.
      */
    public boolean hasIndexIpid() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'index_ipid' field.
      * @return This builder.
      */
    public business.model.strategy.BusinessModelStrategy.Builder clearIndexIpid() {
      index_ipid = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'last_update_timestamp' field.
      * @return The value.
      */
    public long getLastUpdateTimestamp() {
      return last_update_timestamp;
    }


    /**
      * Sets the value of the 'last_update_timestamp' field.
      * @param value The value of 'last_update_timestamp'.
      * @return This builder.
      */
    public business.model.strategy.BusinessModelStrategy.Builder setLastUpdateTimestamp(long value) {
      validate(fields()[2], value);
      this.last_update_timestamp = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'last_update_timestamp' field has been set.
      * @return True if the 'last_update_timestamp' field has been set, false otherwise.
      */
    public boolean hasLastUpdateTimestamp() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'last_update_timestamp' field.
      * @return This builder.
      */
    public business.model.strategy.BusinessModelStrategy.Builder clearLastUpdateTimestamp() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'last_update_loginid' field.
      * @return The value.
      */
    public java.lang.CharSequence getLastUpdateLoginid() {
      return last_update_loginid;
    }


    /**
      * Sets the value of the 'last_update_loginid' field.
      * @param value The value of 'last_update_loginid'.
      * @return This builder.
      */
    public business.model.strategy.BusinessModelStrategy.Builder setLastUpdateLoginid(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.last_update_loginid = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'last_update_loginid' field has been set.
      * @return True if the 'last_update_loginid' field has been set, false otherwise.
      */
    public boolean hasLastUpdateLoginid() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'last_update_loginid' field.
      * @return This builder.
      */
    public business.model.strategy.BusinessModelStrategy.Builder clearLastUpdateLoginid() {
      last_update_loginid = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'partner_ipid' field.
      * @return The value.
      */
    public java.lang.CharSequence getPartnerIpid() {
      return partner_ipid;
    }


    /**
      * Sets the value of the 'partner_ipid' field.
      * @param value The value of 'partner_ipid'.
      * @return This builder.
      */
    public business.model.strategy.BusinessModelStrategy.Builder setPartnerIpid(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.partner_ipid = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'partner_ipid' field has been set.
      * @return True if the 'partner_ipid' field has been set, false otherwise.
      */
    public boolean hasPartnerIpid() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'partner_ipid' field.
      * @return This builder.
      */
    public business.model.strategy.BusinessModelStrategy.Builder clearPartnerIpid() {
      partner_ipid = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'drivers' field.
      * @return The value.
      */
    public java.lang.CharSequence getDrivers() {
      return drivers;
    }


    /**
      * Sets the value of the 'drivers' field.
      * @param value The value of 'drivers'.
      * @return This builder.
      */
    public business.model.strategy.BusinessModelStrategy.Builder setDrivers(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.drivers = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'drivers' field has been set.
      * @return True if the 'drivers' field has been set, false otherwise.
      */
    public boolean hasDrivers() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'drivers' field.
      * @return This builder.
      */
    public business.model.strategy.BusinessModelStrategy.Builder clearDrivers() {
      drivers = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'competencies' field.
      * @return The value.
      */
    public java.lang.CharSequence getCompetencies() {
      return competencies;
    }


    /**
      * Sets the value of the 'competencies' field.
      * @param value The value of 'competencies'.
      * @return This builder.
      */
    public business.model.strategy.BusinessModelStrategy.Builder setCompetencies(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.competencies = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'competencies' field has been set.
      * @return True if the 'competencies' field has been set, false otherwise.
      */
    public boolean hasCompetencies() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'competencies' field.
      * @return This builder.
      */
    public business.model.strategy.BusinessModelStrategy.Builder clearCompetencies() {
      competencies = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'capabilities' field.
      * @return The value.
      */
    public java.lang.CharSequence getCapabilities() {
      return capabilities;
    }


    /**
      * Sets the value of the 'capabilities' field.
      * @param value The value of 'capabilities'.
      * @return This builder.
      */
    public business.model.strategy.BusinessModelStrategy.Builder setCapabilities(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.capabilities = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'capabilities' field has been set.
      * @return True if the 'capabilities' field has been set, false otherwise.
      */
    public boolean hasCapabilities() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'capabilities' field.
      * @return This builder.
      */
    public business.model.strategy.BusinessModelStrategy.Builder clearCapabilities() {
      capabilities = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'client_structure' field.
      * @return The value.
      */
    public java.lang.CharSequence getClientStructure() {
      return client_structure;
    }


    /**
      * Sets the value of the 'client_structure' field.
      * @param value The value of 'client_structure'.
      * @return This builder.
      */
    public business.model.strategy.BusinessModelStrategy.Builder setClientStructure(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.client_structure = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'client_structure' field has been set.
      * @return True if the 'client_structure' field has been set, false otherwise.
      */
    public boolean hasClientStructure() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'client_structure' field.
      * @return This builder.
      */
    public business.model.strategy.BusinessModelStrategy.Builder clearClientStructure() {
      client_structure = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'goals' field.
      * @return The value.
      */
    public java.lang.CharSequence getGoals() {
      return goals;
    }


    /**
      * Sets the value of the 'goals' field.
      * @param value The value of 'goals'.
      * @return This builder.
      */
    public business.model.strategy.BusinessModelStrategy.Builder setGoals(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.goals = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'goals' field has been set.
      * @return True if the 'goals' field has been set, false otherwise.
      */
    public boolean hasGoals() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'goals' field.
      * @return This builder.
      */
    public business.model.strategy.BusinessModelStrategy.Builder clearGoals() {
      goals = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'sales_market_region' field.
      * @return The value.
      */
    public business.model.strategy.code getSalesMarketRegion() {
      return sales_market_region;
    }


    /**
      * Sets the value of the 'sales_market_region' field.
      * @param value The value of 'sales_market_region'.
      * @return This builder.
      */
    public business.model.strategy.BusinessModelStrategy.Builder setSalesMarketRegion(business.model.strategy.code value) {
      validate(fields()[10], value);
      this.sales_market_region = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'sales_market_region' field has been set.
      * @return True if the 'sales_market_region' field has been set, false otherwise.
      */
    public boolean hasSalesMarketRegion() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'sales_market_region' field.
      * @return This builder.
      */
    public business.model.strategy.BusinessModelStrategy.Builder clearSalesMarketRegion() {
      sales_market_region = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'sales_country_150' field.
      * @return The value.
      */
    public java.util.List<java.lang.CharSequence> getSalesCountry150() {
      return sales_country_150;
    }


    /**
      * Sets the value of the 'sales_country_150' field.
      * @param value The value of 'sales_country_150'.
      * @return This builder.
      */
    public business.model.strategy.BusinessModelStrategy.Builder setSalesCountry150(java.util.List<java.lang.CharSequence> value) {
      validate(fields()[11], value);
      this.sales_country_150 = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'sales_country_150' field has been set.
      * @return True if the 'sales_country_150' field has been set, false otherwise.
      */
    public boolean hasSalesCountry150() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'sales_country_150' field.
      * @return This builder.
      */
    public business.model.strategy.BusinessModelStrategy.Builder clearSalesCountry150() {
      sales_country_150 = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public BusinessModelStrategy build() {
      try {
        BusinessModelStrategy record = new BusinessModelStrategy();
        record.avro_fingerprint = fieldSetFlags()[0] ? this.avro_fingerprint : (java.lang.Long) defaultValue(fields()[0]);
        record.index_ipid = fieldSetFlags()[1] ? this.index_ipid : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.last_update_timestamp = fieldSetFlags()[2] ? this.last_update_timestamp : (java.lang.Long) defaultValue(fields()[2]);
        record.last_update_loginid = fieldSetFlags()[3] ? this.last_update_loginid : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.partner_ipid = fieldSetFlags()[4] ? this.partner_ipid : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.drivers = fieldSetFlags()[5] ? this.drivers : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.competencies = fieldSetFlags()[6] ? this.competencies : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.capabilities = fieldSetFlags()[7] ? this.capabilities : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.client_structure = fieldSetFlags()[8] ? this.client_structure : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.goals = fieldSetFlags()[9] ? this.goals : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.sales_market_region = fieldSetFlags()[10] ? this.sales_market_region : (business.model.strategy.code) defaultValue(fields()[10]);
        record.sales_country_150 = fieldSetFlags()[11] ? this.sales_country_150 : (java.util.List<java.lang.CharSequence>) defaultValue(fields()[11]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<BusinessModelStrategy>
    WRITER$ = (org.apache.avro.io.DatumWriter<BusinessModelStrategy>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<BusinessModelStrategy>
    READER$ = (org.apache.avro.io.DatumReader<BusinessModelStrategy>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.avro_fingerprint);

    out.writeString(this.index_ipid);

    out.writeLong(this.last_update_timestamp);

    out.writeString(this.last_update_loginid);

    out.writeString(this.partner_ipid);

    out.writeString(this.drivers);

    out.writeString(this.competencies);

    out.writeString(this.capabilities);

    out.writeString(this.client_structure);

    out.writeString(this.goals);

    if (this.sales_market_region == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeEnum(this.sales_market_region.ordinal());
    }

    if (this.sales_country_150 == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      long size0 = this.sales_country_150.size();
      out.writeArrayStart();
      out.setItemCount(size0);
      long actualSize0 = 0;
      for (java.lang.CharSequence e0: this.sales_country_150) {
        actualSize0++;
        out.startItem();
        out.writeString(e0);
      }
      out.writeArrayEnd();
      if (actualSize0 != size0)
        throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.avro_fingerprint = in.readLong();

      this.index_ipid = in.readString(this.index_ipid instanceof Utf8 ? (Utf8)this.index_ipid : null);

      this.last_update_timestamp = in.readLong();

      this.last_update_loginid = in.readString(this.last_update_loginid instanceof Utf8 ? (Utf8)this.last_update_loginid : null);

      this.partner_ipid = in.readString(this.partner_ipid instanceof Utf8 ? (Utf8)this.partner_ipid : null);

      this.drivers = in.readString(this.drivers instanceof Utf8 ? (Utf8)this.drivers : null);

      this.competencies = in.readString(this.competencies instanceof Utf8 ? (Utf8)this.competencies : null);

      this.capabilities = in.readString(this.capabilities instanceof Utf8 ? (Utf8)this.capabilities : null);

      this.client_structure = in.readString(this.client_structure instanceof Utf8 ? (Utf8)this.client_structure : null);

      this.goals = in.readString(this.goals instanceof Utf8 ? (Utf8)this.goals : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.sales_market_region = null;
      } else {
        this.sales_market_region = business.model.strategy.code.values()[in.readEnum()];
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.sales_country_150 = null;
      } else {
        long size0 = in.readArrayStart();
        java.util.List<java.lang.CharSequence> a0 = this.sales_country_150;
        if (a0 == null) {
          a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("sales_country_150").schema().getTypes().get(1));
          this.sales_country_150 = a0;
        } else a0.clear();
        SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
        for ( ; 0 < size0; size0 = in.arrayNext()) {
          for ( ; size0 != 0; size0--) {
            java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
            e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
            a0.add(e0);
          }
        }
      }

    } else {
      for (int i = 0; i < 12; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.avro_fingerprint = in.readLong();
          break;

        case 1:
          this.index_ipid = in.readString(this.index_ipid instanceof Utf8 ? (Utf8)this.index_ipid : null);
          break;

        case 2:
          this.last_update_timestamp = in.readLong();
          break;

        case 3:
          this.last_update_loginid = in.readString(this.last_update_loginid instanceof Utf8 ? (Utf8)this.last_update_loginid : null);
          break;

        case 4:
          this.partner_ipid = in.readString(this.partner_ipid instanceof Utf8 ? (Utf8)this.partner_ipid : null);
          break;

        case 5:
          this.drivers = in.readString(this.drivers instanceof Utf8 ? (Utf8)this.drivers : null);
          break;

        case 6:
          this.competencies = in.readString(this.competencies instanceof Utf8 ? (Utf8)this.competencies : null);
          break;

        case 7:
          this.capabilities = in.readString(this.capabilities instanceof Utf8 ? (Utf8)this.capabilities : null);
          break;

        case 8:
          this.client_structure = in.readString(this.client_structure instanceof Utf8 ? (Utf8)this.client_structure : null);
          break;

        case 9:
          this.goals = in.readString(this.goals instanceof Utf8 ? (Utf8)this.goals : null);
          break;

        case 10:
          if (in.readIndex() != 1) {
            in.readNull();
            this.sales_market_region = null;
          } else {
            this.sales_market_region = business.model.strategy.code.values()[in.readEnum()];
          }
          break;

        case 11:
          if (in.readIndex() != 1) {
            in.readNull();
            this.sales_country_150 = null;
          } else {
            long size0 = in.readArrayStart();
            java.util.List<java.lang.CharSequence> a0 = this.sales_country_150;
            if (a0 == null) {
              a0 = new SpecificData.Array<java.lang.CharSequence>((int)size0, SCHEMA$.getField("sales_country_150").schema().getTypes().get(1));
              this.sales_country_150 = a0;
            } else a0.clear();
            SpecificData.Array<java.lang.CharSequence> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<java.lang.CharSequence>)a0 : null);
            for ( ; 0 < size0; size0 = in.arrayNext()) {
              for ( ; size0 != 0; size0--) {
                java.lang.CharSequence e0 = (ga0 != null ? ga0.peek() : null);
                e0 = in.readString(e0 instanceof Utf8 ? (Utf8)e0 : null);
                a0.add(e0);
              }
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










