/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package business.model.strategy;
@org.apache.avro.specific.AvroGenerated
public enum code implements org.apache.avro.generic.GenericEnumSymbol<code> {
  M49_150, M49_142, M49_021, M49_756, other  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"code\",\"namespace\":\"business.model.strategy\",\"symbols\":[\"M49_150\",\"M49_142\",\"M49_021\",\"M49_756\",\"other\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
