/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package business.model.strategy;
@org.apache.avro.specific.AvroGenerated
public enum region implements org.apache.avro.generic.GenericEnumSymbol<region> {
  Switzerland, Emea, Apac, Other  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"region\",\"namespace\":\"business.model.strategy\",\"symbols\":[\"Switzerland\",\"Emea\",\"Apac\",\"Other\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
