@startuml

footer "Avro-ElasticSearch Tutorial - cloudburo.net"

database "NoSQL ElasticSearch" {
    folder /EsIndex1  {
    [Avro_JSON_Store]
    }
}

cloud "SchemaRegistry" {
}

package "BoundedContextComponent" {
component Avro_JSON_Store #LightGreen
component ReactMaintainUI #DarkSalmon
component BackendComponent #LightGreen
component ServiceComponent #DarkSalmon
JSON_V100 -up- [ServiceComponent]
JSON_V101 - [ServiceComponent]
[ReactMaintainUI] -> JSON_V101

AvroMsg - [BackendComponent]
[ServiceComponent] -> AvroMsg
[BackendComponent] -> Avro_JSON_Store
[BackendComponent] -up-> SchemaRegistry
}

package "JSONConsumer1" {
component ReactReadUI1 #LightGreen
[ReactReadUI1] -up-> JSON_V100
}

package "AvroMsgConsumer1" {
component DataReadComponent1 #LightGreen
[DataReadComponent1] -up-> AvroMsg
}






@enduml